// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetLuv.Data;

#nullable disable

namespace PetLuv.Migrations
{
    [DbContext(typeof(PetLuvDbContext))]
    [Migration("20260425074211_SeedFinalDataV3")]
    partial class SeedFinalDataV3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetLuv.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Category = "Thức ăn chó",
                            Description = "Hạt dinh dưỡng dành cho chó trưởng thành, cung cấp đầy đủ vitamin...",
                            ImageURL = "1-hat-cho-adult-smartheart.jpg",
                            Price = 100000m,
                            ProductName = "SmartHeart Adult Dog Food",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 2,
                            Category = "Thức ăn chó",
                            Description = "Hạt cao cấp vị cừu dành cho chó, giàu protein và dưỡng chất...",
                            ImageURL = "2-hat-cho-anf-vi-cuu.jpg",
                            Price = 99000m,
                            ProductName = "Hạt hữu cơ ANF 6 vị cừu",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 3,
                            Category = "Thức ăn chó",
                            Description = "Hạt dành riêng cho chó con giống nhỏ từ 2 đến 10 tháng tuổi...",
                            ImageURL = "3-hat-cho-con-royal-canin.jpg",
                            Price = 185000m,
                            ProductName = "Royal Canin Mini Puppy",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 4,
                            Category = "Thức ăn chó",
                            Description = "Thức ăn hạt vị cá hồi dành cho chó con dưới 12 tháng tuổi...",
                            ImageURL = "4-hat-cho-con-today-dinner.jpg",
                            Price = 350000m,
                            ProductName = "Today's Dinner Puppy Salmon",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 5,
                            Category = "Thức ăn chó",
                            Description = "Hạt dinh dưỡng cho chó trưởng thành giống nhỏ, nuôi dưỡng da lông...",
                            ImageURL = "5-hat-cho-luv-care-truong-thanh.jpg",
                            Price = 310000m,
                            ProductName = "LuvCare Adult Small Breed",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 6,
                            Category = "Thức ăn chó",
                            Description = "Thành phần chính là thịt cừu và gạo lứt, lý tưởng cho tiêu hóa...",
                            ImageURL = "6-hat-cho-nutrience-vi-cuu.jpg",
                            Price = 520000m,
                            ProductName = "Nutrience Original Adult",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 7,
                            Category = "Thức ăn chó",
                            Description = "Thức ăn siêu cao cấp vị cá hồi dành cho chó trưởng thành...",
                            ImageURL = "7-hat-cho-reflex-vi-ca-hoi.jpg",
                            Price = 320000m,
                            ProductName = "Reflex Plus Adult Salmon",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 8,
                            Category = "Thức ăn chó",
                            Description = "Hạt dinh dưỡng vị gà và rau củ cho chó trưởng thành trên 1 năm tuổi...",
                            ImageURL = "8-hat-cho-truong-thanh-pedigree.jpg",
                            Price = 110000m,
                            ProductName = "Pedigree Adult Chicken",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 9,
                            Category = "Thức ăn mèo",
                            Description = "Thức ăn cho mọi lứa tuổi, giúp kiểm soát búi lông và tăng thị lực...",
                            ImageURL = "9-hat-meo-cat-eye.jpg",
                            Price = 820000m,
                            ProductName = "Cat's Eye Kitten & Cat",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 10,
                            Category = "Thức ăn mèo",
                            Description = "Dành cho mèo con từ 2–12 tháng tuổi, hỗ trợ phát triển toàn diện...",
                            ImageURL = "10-hat-meo-con-whiskas.jpg",
                            Price = 120000m,
                            ProductName = "Whiskas Junior Cat Food",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 11,
                            Category = "Thức ăn mèo",
                            Description = "Hương vị hải sản thơm ngon, tăng cường thị lực cho mèo...",
                            ImageURL = "11-hat-meo-meo.jpg",
                            Price = 95000m,
                            ProductName = "Me-O Adult Cat Food",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 12,
                            Category = "Thức ăn mèo",
                            Description = "Vị mực hấp dẫn, bổ sung taurine tốt cho mắt và tim mạch...",
                            ImageURL = "12-hat-meo-minino.jpg",
                            Price = 90000m,
                            ProductName = "Minino Yum Adult Cat",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 13,
                            Category = "Thức ăn mèo",
                            Description = "Hạt không chứa ngũ cốc, phù hợp cho mèo nhạy cảm tiêu hóa...",
                            ImageURL = "13-hat-meo-mr-vet.jpg",
                            Price = 130000m,
                            ProductName = "Mr.Vet Grain Free Tuna",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 14,
                            Category = "Thức ăn mèo",
                            Description = "Giàu protein từ thịt tươi bò, heo rừng và cá sấy lạnh...",
                            ImageURL = "14-hat-meo-nutrience.jpg",
                            Price = 280000m,
                            ProductName = "Nutrience SubZero Red",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 15,
                            Category = "Thức ăn mèo",
                            Description = "Dành riêng cho mèo con, dễ tiêu hóa và tăng cường miễn dịch...",
                            ImageURL = "15-hat-meo-reflex.jpg",
                            Price = 95000m,
                            ProductName = "Reflex Plus Kitten Chicken",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 16,
                            Category = "Thức ăn mèo",
                            Description = "Dành cho mèo mẹ mang thai và mèo con từ 1–4 tháng tuổi...",
                            ImageURL = "16-hat-meo-royal-canin.jpg",
                            Price = 220000m,
                            ProductName = "Royal Canin Mother & Babycat",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 17,
                            Category = "Dịch vụ",
                            Description = "Không gian sạch sẽ, chăm sóc 24/7 giúp thú cưng thoải mái...",
                            ImageURL = "service-hotel-1.jpg",
                            Price = 200000m,
                            ProductName = "Pet Hotel - Lưu trú",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 18,
                            Category = "Dịch vụ",
                            Description = "Môi trường an toàn, đội ngũ chăm sóc tận tâm chu đáo...",
                            ImageURL = "service-hotel-2.jpg",
                            Price = 150000m,
                            ProductName = "Dịch vụ giữ thú cưng",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 19,
                            Category = "Dịch vụ",
                            Description = "Tắm, cắt tỉa và chăm sóc lông chuyên nghiệp giúp thú cưng sạch thơm...",
                            ImageURL = "service-spa-1.jpg",
                            Price = 300000m,
                            ProductName = "Pet Spa & Grooming",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 20,
                            Category = "Dịch vụ",
                            Description = "Quy trình chăm sóc nhẹ nhàng, giúp thú cưng thư giãn nhất...",
                            ImageURL = "service-spa-2.jpg",
                            Price = 250000m,
                            ProductName = "Chăm sóc & làm đẹp",
                            Stock = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
