// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetLuv.Data;

#nullable disable

namespace PetLuv.Migrations
{
    [DbContext(typeof(PetLuvDbContext))]
    [Migration("20260504132247_AddCartTable")]
    partial class AddCartTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetLuv.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("PetLuv.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Category = "Thức ăn chó",
                            Description = "Hạt dinh dưỡng cân bằng protein và chất béo giúp chó trưởng thành duy trì vóc dáng và sức khỏe tốt.",
                            ImageURL = "1-hat-cho-adult-smartheart.jpg",
                            Price = 100000m,
                            ProductName = "SmartHeart Adult Dog Food",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 2,
                            Category = "Thức ăn chó",
                            Description = "Sản phẩm hữu cơ với thành phần thịt cừu tươi ngon, hỗ trợ hệ tiêu hóa và làm mượt lông cho cún yêu.",
                            ImageURL = "2-hat-cho-anf-vi-cuu.jpg",
                            Price = 99000m,
                            ProductName = "Hạt hữu cơ ANF 6 vị cừu",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 3,
                            Category = "Thức ăn chó",
                            Description = "Công thức đặc biệt dành cho chó con giống nhỏ, bổ sung DHA giúp phát triển trí não và tăng cường miễn dịch.",
                            ImageURL = "3-hat-cho-con-royal-canin.jpg",
                            Price = 185000m,
                            ProductName = "Royal Canin Mini Puppy",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 4,
                            Category = "Thức ăn chó",
                            Description = "Thức ăn hạt vị cá hồi giàu Omega-3, không gây dị ứng, phù hợp cho sự phát triển toàn diện của chó con.",
                            ImageURL = "4-hat-cho-con-today-dinner.jpg",
                            Price = 350000m,
                            ProductName = "Today's Dinner Puppy Salmon",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 5,
                            Category = "Thức ăn chó",
                            Description = "Dinh dưỡng chuyên biệt cho chó giống nhỏ, giúp giảm mảng bám trên răng và ổn định hệ đường ruột.",
                            ImageURL = "5-hat-cho-luv-care-truong-thanh.jpg",
                            Price = 310000m,
                            ProductName = "LuvCare Adult Small Breed",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 6,
                            Category = "Thức ăn chó",
                            Description = "Thành phần tự nhiên từ thịt cừu và gạo lứt, không chứa chất bảo quản, cực kỳ an toàn cho sức khỏe thú cưng.",
                            ImageURL = "6-hat-cho-nutrience-vi-cuu.jpg",
                            Price = 520000m,
                            ProductName = "Nutrience Original Adult",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 7,
                            Category = "Thức ăn chó",
                            Description = "Thức ăn siêu cao cấp với cá hồi Nauy, giúp cải thiện tình trạng da liễu và kích thích vị giác chó kén ăn.",
                            ImageURL = "7-hat-cho-reflex-vi-ca-hoi.jpg",
                            Price = 320000m,
                            ProductName = "Reflex Plus Adult Salmon",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 8,
                            Category = "Thức ăn chó",
                            Description = "Sự kết hợp hoàn hảo giữa thịt gà và rau củ, cung cấp đầy đủ vitamin và khoáng chất cho hoạt động hàng ngày.",
                            ImageURL = "8-hat-cho-truong-thanh-pedigree.jpg",
                            Price = 110000m,
                            ProductName = "Pedigree Adult Chicken",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 9,
                            Category = "Thức ăn mèo",
                            Description = "Hạt dinh dưỡng tổng hợp cho mọi lứa tuổi, hỗ trợ đào thải búi lông và giảm mùi hôi chất thải của mèo.",
                            ImageURL = "9-hat-meo-cat-eye.jpg",
                            Price = 820000m,
                            ProductName = "Cat's Eye Kitten & Cat",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 10,
                            Category = "Thức ăn mèo",
                            Description = "Thức ăn giàu Canxi và Phospho giúp mèo con phát triển xương chắc khỏe trong giai đoạn từ 2 đến 12 tháng.",
                            ImageURL = "10-hat-meo-con-whiskas.jpg",
                            Price = 120000m,
                            ProductName = "Whiskas Junior Cat Food",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 11,
                            Category = "Thức ăn mèo",
                            Description = "Vị hải sản thơm ngon khó cưỡng, bổ sung Taurine giúp mắt mèo sáng tinh anh và bảo vệ hệ tim mạch.",
                            ImageURL = "11-hat-meo-meo.jpg",
                            Price = 95000m,
                            ProductName = "Me-O Adult Cat Food",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 12,
                            Category = "Thức ăn mèo",
                            Description = "Hạt vị mực hấp dẫn, kết hợp các sợi xơ tự nhiên giúp hệ tiêu hóa của mèo hoạt động trơn tru hơn.",
                            ImageURL = "12-hat-meo-minino.jpg",
                            Price = 90000m,
                            ProductName = "Minino Yum Adult Cat",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 13,
                            Category = "Thức ăn mèo",
                            Description = "Công thức Grain-Free không ngũ cốc, giàu đạm từ cá ngừ tươi, dành riêng cho các bé mèo có hệ tiêu hóa nhạy cảm.",
                            ImageURL = "13-hat-meo-mr-vet.jpg",
                            Price = 130000m,
                            ProductName = "Mr.Vet Grain Free Tuna",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 14,
                            Category = "Thức ăn mèo",
                            Description = "Thức ăn sấy lạnh cao cấp từ thịt bò và cá, cung cấp năng lượng vượt trội cho mèo năng động.",
                            ImageURL = "14-hat-meo-nutrience.jpg",
                            Price = 280000m,
                            ProductName = "Nutrience SubZero Red",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 15,
                            Category = "Thức ăn mèo",
                            Description = "Dinh dưỡng dễ hấp thụ từ thịt gà sạch, giúp mèo con lớn nhanh và có hệ miễn dịch vượt trội.",
                            ImageURL = "15-hat-meo-reflex.jpg",
                            Price = 95000m,
                            ProductName = "Reflex Plus Kitten Chicken",
                            Stock = 0
                        },
                        new
                        {
                            ProductID = 16,
                            Category = "Thức ăn mèo",
                            Description = "Sản phẩm đặc chế cho mèo mẹ đang mang thai và mèo con mới tập ăn, kết cấu hạt mềm dễ nhai.",
                            ImageURL = "16-hat-meo-royal-canin.jpg",
                            Price = 220000m,
                            ProductName = "Royal Canin Mother & Babycat",
                            Stock = 0
                        });
                });

            modelBuilder.Entity("PetLuv.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PetLuv.Models.Cart", b =>
                {
                    b.HasOne("PetLuv.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetLuv.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
